name: planify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  location: ^8.0.0
  persistent_bottom_nav_bar: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
